import mongoose from 'mongoose';
import bcrypt from 'bcrypt';
import { env } from '../config/env';
import { Topic } from '../models/Topic';
import { Problem } from '../models/Problem';
import { User } from '../models/User';

const TOPICS = [
  { title: 'Arrays', slug: 'arrays', icon: '', description: 'Foundation of DSA — arrays, hashing, sliding window, and two-pointer patterns.', order: 1 },
  { title: 'Strings', slug: 'strings', icon: '', description: 'String manipulation, pattern matching, and sliding window on character arrays.', order: 2 },
  { title: 'Binary Search', slug: 'binary-search', icon: '', description: 'Divide-and-conquer search on sorted arrays, rotated arrays, and answer spaces.', order: 3 },
  { title: 'Recursion & Backtracking', slug: 'recursion', icon: '', description: 'Recursive thinking, combinatorics, and constraint-based pruning.', order: 4 },
  { title: 'Linked List', slug: 'linked-list', icon: '', description: 'Pointer manipulation, fast & slow pointers, and list re-structuring.', order: 5 },
  { title: 'Stacks & Queues', slug: 'stacks-queues', icon: '', description: 'Monotonic stacks, LRU cache, sliding window max, and queue-based BFS.', order: 6 },
  { title: 'Binary Trees', slug: 'binary-trees', icon: '', description: 'DFS, BFS, tree DP, and classic binary tree traversal problems.', order: 7 },
  { title: 'BST', slug: 'bst', icon: '', description: 'Binary Search Trees — insertion, deletion, balancing, and order statistics.', order: 8 },
  { title: 'Heaps', slug: 'heaps', icon: '', description: 'Min-heap, max-heap, priority queues, and top-K problems.', order: 9 },
  { title: 'Tries', slug: 'tries', icon: '', description: 'Prefix trees for autocomplete, XOR tricks, and word dictionary problems.', order: 10 },
  { title: 'Graphs', slug: 'graphs', icon: '', description: 'BFS, DFS, topological sort, shortest paths, and MST algorithms.', order: 11 },
  { title: 'Dynamic Programming', slug: 'dp', icon: '', description: 'Memoization and tabulation across 1D, 2D, and string DP problems.', order: 12 },
  { title: 'Greedy', slug: 'greedy', icon: '', description: 'Locally optimal choices — intervals, scheduling, and greedy proofs.', order: 13 },
  { title: 'Miscellaneous', slug: 'misc', icon: '', description: 'Bit manipulation, math tricks, and mixed-paradigm problems.', order: 14 },
];

interface ProblemSeed {
  topicSlug: string;
  subtopic: string;
  title: string;
  slug: string;
  difficulty: 'easy' | 'medium' | 'hard';
  order: number;
  resources: { youtubeUrl: string; leetcodeUrl: string; articleUrl: string; codeforcesUrl: string };
  tags: string[];
  companyTags: string[];
  avgTime: string;
}

const PROBLEMS: ProblemSeed[] = [
  { topicSlug: 'arrays', subtopic: 'Array (Part 1)', title: 'Majority Element', slug: 'majority-element', difficulty: 'easy', order: 1, resources: { youtubeUrl: 'https://youtu.be/_xqIp2rj8bo?t=882', leetcodeUrl: 'https://leetcode.com/problems/majority-element/description/', articleUrl: 'https://dsa.apnacollege.in/majority-element', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Google'], avgTime: '10-20 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 1)', title: 'Repeat & missing number', slug: 'repeat-missing-number', difficulty: 'easy', order: 2, resources: { youtubeUrl: 'https://youtu.be/0Fxc_jKj2vo?t=1321', leetcodeUrl: 'https://leetcode.com/problems/find-missing-and-repeated-values/description/', articleUrl: 'https://dsa.apnacollege.in/repeat-missing-number', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 1)', title: 'Merge 2 sorted array without extra space', slug: 'merge-2-sorted-array-without-extra-space', difficulty: 'easy', order: 3, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=-1cLK6PaLsQ&list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt&index=27', leetcodeUrl: 'https://leetcode.com/problems/merge-sorted-array/description/', articleUrl: 'https://dsa.apnacollege.in/merge-2-sorted-array-without-extra-space', codeforcesUrl: '' }, tags: [], companyTags: ['Quikr', 'Snapdeal', 'Synopsys', 'Zoho', 'Juniper', 'Goldman Sachs', 'Brocade', 'Amdocs', 'Networks', 'Linkedin', 'Microsoft', 'Adobe'], avgTime: '10-20 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 1)', title: 'Single Number', slug: 'single-number', difficulty: 'easy', order: 4, resources: { youtubeUrl: 'https://youtu.be/NWg38xWYzEg?t=1393', leetcodeUrl: 'https://leetcode.com/problems/single-number/description/', articleUrl: 'https://dsa.apnacollege.in/single-number', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Amazon', 'Microsoft', 'Adobe', 'Zoho', 'Airbnb', 'Qualcomm', 'Uber', 'Google', 'TCS', 'Meta'], avgTime: '10-20 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 1)', title: 'Stock Buy & Sell', slug: 'stock-buy-sell', difficulty: 'easy', order: 5, resources: { youtubeUrl: 'https://youtu.be/WBzZCm46mFo?t=835', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/', articleUrl: 'https://dsa.apnacollege.in/stock-buy-sell', codeforcesUrl: '' }, tags: [], companyTags: ['Walmart', 'Swiggy', 'Google', 'Salesforce', 'Quikr', 'Media.Net', 'Pubmatic', 'Paytm', 'Oracle', 'Ola', 'Microsoft', 'MakeMyTrip', 'Intuit', 'Goldman Sachs', 'Flipkart', 'Amazon', 'DE Shaw', 'Directi'], avgTime: '10-20 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 1)', title: 'Pow (x^n)', slug: 'pow-xn', difficulty: 'medium', order: 6, resources: { youtubeUrl: 'https://youtu.be/WBzZCm46mFo?t=21', leetcodeUrl: 'https://leetcode.com/problems/powx-n/description/', articleUrl: 'https://dsa.apnacollege.in/pow-xn', codeforcesUrl: '' }, tags: [], companyTags: ['Linkedin', 'Amazon', 'Meta', 'Citadel', 'JP morgan', 'Oracle', 'Microsoft', 'Google', 'Salesforce'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 2)', title: 'Kadane\'s Algorithm', slug: 'kadanes-algorithm', difficulty: 'medium', order: 7, resources: { youtubeUrl: 'https://youtu.be/9IZYqostl2M?t=760', leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/description/', articleUrl: 'https://dsa.apnacollege.in/kadanes-algorithm', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Facebook'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 2)', title: 'Container with most water', slug: 'container-with-most-water', difficulty: 'medium', order: 8, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=EbkMABpP52U', leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water/description/', articleUrl: 'https://dsa.apnacollege.in/container-with-most-water', codeforcesUrl: '' }, tags: [], companyTags: ['Dunzo', 'Flipkart'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 2)', title: 'Sort array of 0s, 1s & 2s', slug: 'sort-array-of-0s-1s-2s', difficulty: 'medium', order: 9, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=J48aGjfjYTI&list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt&index=26', leetcodeUrl: 'https://leetcode.com/problems/sort-colors/description/', articleUrl: 'https://dsa.apnacollege.in/sort-array-of-0s-1s-2s', codeforcesUrl: '' }, tags: [], companyTags: ['MakeMyTrip', 'Amazon', 'Microsoft'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 2)', title: '3Sum', slug: '3sum', difficulty: 'medium', order: 10, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=K-RsltkN63w', leetcodeUrl: 'https://leetcode.com/problems/3sum/description/', articleUrl: 'https://dsa.apnacollege.in/3sum', codeforcesUrl: '' }, tags: [], companyTags: ['Times Internet', 'Snapdeal', 'Morgan Stanley', 'Samsung', 'Microsoft', 'Amazon', 'Adobe'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 2)', title: '4Sum', slug: '4sum', difficulty: 'medium', order: 11, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=X6sL8JTROLY', leetcodeUrl: 'https://leetcode.com/problems/4sum/description/', articleUrl: 'https://dsa.apnacollege.in/4sum', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'OYO', 'Uber', 'Microsoft', 'Apple', 'TCS', 'Rubrik'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 2)', title: 'Search in 2d matrix', slug: 'search-in-2d-matrix', difficulty: 'medium', order: 12, resources: { youtubeUrl: 'https://youtu.be/LEFFjgt5i6w?t=882', leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Cisco', 'Uber', 'Visa', 'Amazon', 'Goldman Sachs', 'Meta', 'Apple'], avgTime: '20-30 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 3)', title: 'Next permutation', slug: 'next-permutation', difficulty: 'medium', order: 13, resources: { youtubeUrl: 'https://youtu.be/-1cLK6PaLsQ?list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt&t=967', leetcodeUrl: 'https://leetcode.com/problems/next-permutation/description/', articleUrl: 'https://dsa.apnacollege.in/next-permutation', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Goldman Sachs', 'Adobe'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 3)', title: 'Merge overlapping intervals', slug: 'merge-overlapping-intervals', difficulty: 'medium', order: 14, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/merge-intervals/description/', articleUrl: 'https://dsa.apnacollege.in/merge-overlapping-intervals', codeforcesUrl: '' }, tags: [], companyTags: ['Google'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 3)', title: 'Longest substring without repeating', slug: 'longest-substring-without-repeating', difficulty: 'medium', order: 15, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/description/', articleUrl: 'https://dsa.apnacollege.in/longest-substring-without-repeating', codeforcesUrl: '' }, tags: [], companyTags: ['Morgan Stanley', 'Amazon'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 3)', title: 'Set matrix zeroes', slug: 'set-matrix-zeroes', difficulty: 'medium', order: 16, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/set-matrix-zeroes/description/', articleUrl: 'https://dsa.apnacollege.in/set-matrix-zeroes', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Microsoft'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 3)', title: 'Word search', slug: 'word-search', difficulty: 'medium', order: 17, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/word-search/description/', articleUrl: 'https://dsa.apnacollege.in/word-search', codeforcesUrl: '' }, tags: [], companyTags: ['Ola', 'Goldman Sachs', 'Google'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 3)', title: 'Product of array except self', slug: 'product-of-array-except-self', difficulty: 'medium', order: 18, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=TW2m8m_FNJE', leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self/description/', articleUrl: 'https://dsa.apnacollege.in/product-of-array-except-self', codeforcesUrl: '' }, tags: [], companyTags: ['Ola', 'Goldman Sachs', 'Google'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 4)', title: 'Subarray sum equals k', slug: 'subarray-sum-equals-k', difficulty: 'medium', order: 19, resources: { youtubeUrl: 'https://youtu.be/KDH4mhFVvHw?si=LGsc4jbq5QZ0QnsO', leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k/description/', articleUrl: 'https://dsa.apnacollege.in/subarray-sum-equals-k', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Snapdeal'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 4)', title: 'Find Duplicate', slug: 'find-duplicate', difficulty: 'medium', order: 20, resources: { youtubeUrl: 'https://youtu.be/0Fxc_jKj2vo?t=2000', leetcodeUrl: 'https://leetcode.com/problems/find-the-duplicate-number/', articleUrl: 'https://dsa.apnacollege.in/find-duplicate', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Goldman Sachs', 'IBM', 'Adobe', 'Yahoo'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 4)', title: 'Count Inversions', slug: 'count-inversions', difficulty: 'hard', order: 21, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=ynnWDBTdVi0', leetcodeUrl: 'https://www.hackerrank.com/challenges/ctci-merge-sort/problem', articleUrl: 'https://dsa.apnacollege.in/count-inversions', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon', 'Salesforce'], avgTime: '40-60 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 4)', title: 'Spiral Matrix', slug: 'spiral-matrix', difficulty: 'medium', order: 22, resources: { youtubeUrl: 'https://youtu.be/XMpdvwUObho?si=opqd98A9rm0GiTMG', leetcodeUrl: 'https://leetcode.com/problems/spiral-matrix/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Flipkart', 'Societe generale', 'Apple'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 4)', title: 'Search in Sorted matrix II', slug: 'search-in-sorted-matrix-ii', difficulty: 'medium', order: 23, resources: { youtubeUrl: 'https://youtu.be/LEFFjgt5i6w?si=E2QRmGvkNcrrv64t', leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Oracle', 'Amazon', 'Meta', 'Apple', 'TCS'], avgTime: '20-25 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 5)', title: 'Trapping Rainwater', slug: 'trapping-rainwater', difficulty: 'hard', order: 24, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=UHHp8USwx4M', leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water/description/', articleUrl: 'https://dsa.apnacollege.in/trapping-rainwater', codeforcesUrl: '' }, tags: [], companyTags: ['Samsung'], avgTime: '40-60 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 5)', title: 'Sliding Window Maximum', slug: 'sliding-window-maximum', difficulty: 'hard', order: 25, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=XwG5cozqfaM', leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum/description/', articleUrl: 'https://dsa.apnacollege.in/sliding-window-maximum', codeforcesUrl: '' }, tags: [], companyTags: ['Flipkart', 'Google', 'Microsoft', 'Directi', 'Amazon'], avgTime: '50-70 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 5)', title: 'Largest Rectangle in a Histogram', slug: 'largest-rectangle-in-a-histogram', difficulty: 'hard', order: 26, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=ysy1o-QEj3k', leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/description/', articleUrl: 'https://dsa.apnacollege.in/largest-rectangle-in-a-histogram', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Doordash', 'Google', 'Myntra', 'DE Shaw', 'Adobe', 'TCS'], avgTime: '40-60 min' },
  { topicSlug: 'arrays', subtopic: 'Array (Part 5)', title: 'Reverse Pairs', slug: 'reverse-pairs', difficulty: 'hard', order: 27, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/reverse-pairs/description/', articleUrl: 'https://dsa.apnacollege.in/reverse-pairs', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Apple', 'Amazon', 'Uber'], avgTime: '40-60 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 1)', title: 'Valid Palindrome', slug: 'valid-palindrome', difficulty: 'easy', order: 1, resources: { youtubeUrl: 'https://youtu.be/dSRFgEs3a6A?si=WUcnajw8nRAsHlb4', leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome/description/', articleUrl: 'https://dsa.apnacollege.in/valid-palindrome', codeforcesUrl: '' }, tags: [], companyTags: ['Morgan Stanley', 'Amazon', 'DE Shaw', 'Facebook', 'Cisco', 'FactSet', 'Paytm', 'Zoho'], avgTime: '10-20 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 1)', title: 'Valid Anagram', slug: 'valid-anagram', difficulty: 'easy', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/valid-anagram/description/', articleUrl: 'https://dsa.apnacollege.in/valid-anagram', codeforcesUrl: '' }, tags: [], companyTags: ['Flipkart', 'Directi', 'Media.Net', 'Google', 'Adobe', 'Nagarro'], avgTime: '10-20 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 1)', title: 'Reverse Words in String', slug: 'reverse-words-in-string', difficulty: 'medium', order: 3, resources: { youtubeUrl: 'https://youtu.be/RitppzIdMCo?si=bLqHmxS1_C_HlODW', leetcodeUrl: 'https://leetcode.com/problems/reverse-words-in-a-string/description/', articleUrl: 'https://dsa.apnacollege.in/reverse-words-in-string', codeforcesUrl: '' }, tags: [], companyTags: ['TCS', 'Infosys', 'Nvidia', 'Accenture', 'Google', 'Zoho', 'Amazon', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 1)', title: 'Remove All Occurrences', slug: 'remove-all-occurrences', difficulty: 'medium', order: 4, resources: { youtubeUrl: 'https://youtu.be/dSRFgEs3a6A?si=OP8Zzi_5VDRzKwju', leetcodeUrl: 'https://leetcode.com/problems/remove-all-occurrences-of-a-substring/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['IBM', 'Microsoft', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 1)', title: 'Permutation in String', slug: 'permutation-in-string', difficulty: 'medium', order: 5, resources: { youtubeUrl: 'https://youtu.be/VXewy91P0S4?si=LpzKLUD9PZf_9Nra', leetcodeUrl: 'https://leetcode.com/problems/permutation-in-string/description/', articleUrl: 'https://dsa.apnacollege.in/permutation-in-string', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Goldman Sachs', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 1)', title: 'String Compression', slug: 'string-compression', difficulty: 'medium', order: 6, resources: { youtubeUrl: 'https://youtu.be/cAB15h6-sWA?si=eS5enMt3366LGh-7', leetcodeUrl: 'https://leetcode.com/problems/string-compression/description/', articleUrl: 'https://dsa.apnacollege.in/string-compression', codeforcesUrl: '' }, tags: [], companyTags: ['GoDaddy', 'Amazon', 'Salesforce', 'Yandex', 'Pinterest', 'Meta'], avgTime: '20-30 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 2)', title: 'Longest Common Prefix', slug: 'longest-common-prefix', difficulty: 'easy', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Meta', 'TCS', 'Infosys', 'Deloitte', 'Apple', 'Microsoft', 'Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 2)', title: 'Group Anagrams', slug: 'group-anagrams', difficulty: 'medium', order: 8, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/group-anagrams/description/', articleUrl: 'https://dsa.apnacollege.in/group-anagrams', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Salesforce', 'TCS', 'Nvidia', 'Meta', 'Amazon', 'Oracle', 'Adobe', 'PayPal'], avgTime: '20-30 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 2)', title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'hard', order: 9, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/description/', articleUrl: 'https://dsa.apnacollege.in/minimum-window-substring', codeforcesUrl: '' }, tags: [], companyTags: ['MakeMyTrip', 'Flipkart', 'Google', 'Amazon', 'Airbnb', 'Atlassian', 'Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 2)', title: 'KMP Algorithm', slug: 'kmp-algorithm', difficulty: 'hard', order: 10, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-happy-prefix/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon'], avgTime: '40-60 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 2)', title: 'Robin-Karp Algorithm', slug: 'robin-karp-algorithm', difficulty: 'hard', order: 11, resources: { youtubeUrl: '', leetcodeUrl: '', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'strings', subtopic: 'Strings (Part 2)', title: 'Reverse Words in String', slug: 'reverse-words-in-string-2', difficulty: 'medium', order: 12, resources: { youtubeUrl: 'https://www.youtube.com/embed/RitppzIdMCo', leetcodeUrl: 'https://leetcode.com/problems/reverse-words-in-a-string/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Meta', 'TCS', 'Accenture', 'Infosys', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Peak Index in Mountain Array', slug: 'peak-index-in-mountain-array', difficulty: 'medium', order: 1, resources: { youtubeUrl: 'https://youtu.be/RjxD6UXGlhc?si=cw3-q4z5Z005_R5G', leetcodeUrl: 'https://leetcode.com/problems/peak-index-in-a-mountain-array/description/', articleUrl: 'https://dsa.apnacollege.in/peak-index-in-mountain-array', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'DE Shaw', 'Meta', 'Amazon', 'Microsoft', 'Adobe', 'Accenture', 'TCS'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Search in Rotated Sorted Array ', slug: 'search-in-rotated-sorted', difficulty: 'medium', order: 2, resources: { youtubeUrl: 'https://youtu.be/6WNZQBHWQJs?si=MihpDB7KJ2aCOO9u', leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/description/', articleUrl: 'https://dsa.apnacollege.in/search-in-rotated-sorted', codeforcesUrl: '' }, tags: [], companyTags: ['MakeMyTrip', 'Visa', 'Google', 'Paytm', 'Goldman Sachs', 'Intuit', 'Hike', 'Microsoft', 'DE Shaw', 'Amazon', 'Adobe', 'Flipkart'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Single Element in Sorted Array', slug: 'single-element-in-sorted-array', difficulty: 'medium', order: 3, resources: { youtubeUrl: 'https://youtu.be/qsbCBduIs40?si=RDuU5EnemxN6j6mW', leetcodeUrl: 'https://leetcode.com/problems/single-element-in-a-sorted-array/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Infosys', 'TCS', 'Blinkit', 'Flipkart', 'Apple', 'Meta', 'Google', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Aggressive Cows', slug: 'aggressive-cows', difficulty: 'medium', order: 4, resources: { youtubeUrl: 'https://youtu.be/7wOzDqsfXy0?si=c6eVx-Wc-1GIrj0y', leetcodeUrl: 'https://www.spoj.com/problems/AGGRCOW/', articleUrl: 'https://dsa.apnacollege.in/aggressive-cows', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Allocate Minimum Pages', slug: 'allocate-minimum-pages', difficulty: 'medium', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/minimized-maximum-of-products-distributed-to-any-store/description/', articleUrl: 'https://dsa.apnacollege.in/allocate-minimum-pages', codeforcesUrl: '' }, tags: [], companyTags: ['Salesforce', 'Google', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Painter’s Partition', slug: 'painters-partition', difficulty: 'medium', order: 6, resources: { youtubeUrl: 'https://youtu.be/srsFN5OHBgw?si=k7hAiRe8HnPi4NHF', leetcodeUrl: 'https://www.hackerearth.com/problem/algorithm/painters-partition/', articleUrl: 'https://dsa.apnacollege.in/painters-partition', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Oracle', 'Microsoft', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'binary-search', subtopic: 'Binary Search', title: 'Median of 2 Sorted Arrays', slug: 'median-of-2-sorted-arrays', difficulty: 'hard', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', articleUrl: 'https://dsa.apnacollege.in/median-of-2-sorted-arrays', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Flipkart', 'DE Shaw', 'Adobe', 'Salesforce', 'Oracle', 'Microsoft', 'Amazon', 'Meta'], avgTime: '40-60 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Combination Sum I', slug: 'combination-sum-i', difficulty: 'medium', order: 1, resources: { youtubeUrl: 'https://youtu.be/jkgZw2WEaqA?si=3YpIrvX_36R4MOa2', leetcodeUrl: 'https://leetcode.com/problems/combination-sum/description/', articleUrl: 'https://dsa.apnacollege.in/combination-sum-i', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Amazon', 'DE Shaw', 'Salesforce', 'Oracle', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Combination Sum II', slug: 'combination-sum-ii', difficulty: 'medium', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/combination-sum-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Oracle', 'Microsoft', 'Amazon', 'Adobe', 'Goldman Sachs'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Palindrome Partitioning', slug: 'palindrome-partitioning', difficulty: 'medium', order: 3, resources: { youtubeUrl: 'https://youtu.be/aZ0B1eWkSVU?si=4DLqSJjkT9iT0JMS', leetcodeUrl: 'https://leetcode.com/problems/palindrome-partitioning/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Microsoft', 'Amazon', 'Adobe', 'Infosys'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'N Queens', slug: 'n-queens', difficulty: 'hard', order: 4, resources: { youtubeUrl: 'https://youtu.be/BdSJnIdR-4s?si=w5K9IKkKeecaXaq7', leetcodeUrl: 'https://leetcode.com/problems/n-queens/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['TCS', 'Apple', 'Citadel', 'Meta', 'Google', 'Microsoft', 'Oracle', 'Salesforce', 'Amazon'], avgTime: '40-60 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Sudoku Solver', slug: 'sudoku-solver', difficulty: 'hard', order: 5, resources: { youtubeUrl: 'https://youtu.be/70cP3qtJp-s?si=Mi8inCRxN2n-VlmR', leetcodeUrl: 'https://leetcode.com/problems/sudoku-solver/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Citadel', 'Oracle', 'Microsoft', 'Amazon', 'Meta', 'Goldman Sachs', 'Intuit', 'Google'], avgTime: '40-60 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'M-Coloring Problem', slug: 'm-coloring-problem', difficulty: 'medium', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Knights Tour', slug: 'knights-tour', difficulty: 'medium', order: 7, resources: { youtubeUrl: 'https://youtu.be/Sp1jzttFVdE', leetcodeUrl: 'https://leetcode.com/problems/check-knight-tour-configuration/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Google', 'Microsoft', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Subsets II', slug: 'subsets-ii', difficulty: 'medium', order: 8, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=pNzljlzDCiI&t=2s', leetcodeUrl: 'https://leetcode.com/problems/subsets-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Swiggy', 'Apple', 'Meta', 'TCS', 'Uber', 'Flipkart', 'Adobe', 'Microsoft', 'Amazon', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Merge Sort', slug: 'merge-sort', difficulty: 'easy', order: 9, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=cQDtOBTy7_Y&t=12s', leetcodeUrl: 'https://leetcode.com/problems/sort-an-array/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Infosys', 'Oracle', 'Adobe', 'Amazon', 'Apple', 'Meta', 'TCS'], avgTime: '10-20 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Rat in a Maze', slug: 'rat-in-a-maze', difficulty: 'medium', order: 10, resources: { youtubeUrl: 'https://youtu.be/D8Yze9CDDAw?si=4HiqdNuf2gYtcMMH', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'recursion', subtopic: 'Recursion & Backtracking', title: 'Count Inversions', slug: 'count-inversions-2', difficulty: 'hard', order: 11, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=ynnWDBTdVi0&t=69s', leetcodeUrl: 'https://leetcode.com/problems/count-the-number-of-inversions/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Salesforce', 'Amazon'], avgTime: '40-60 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 1)', title: 'Middle of a Linked List', slug: 'middle-of-a-linked-list', difficulty: 'easy', order: 1, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=nzaHG0dme4g', leetcodeUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Amazon', 'Google', 'Intuit', 'Qualcomm', 'Goldman Sachs'], avgTime: '10-20 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 1)', title: 'Reverse Linked List ', slug: 'reverse-linked-list-i', difficulty: 'easy', order: 2, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=R-CKBYnOv1U', leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'PayPal', 'Microsoft', 'Amazon', 'Oracle', 'Adobe', 'Qualcomm', 'TCS', 'Apple', 'Meta', 'JP morgan'], avgTime: '10-20 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 1)', title: 'Remove Cycle in a LL', slug: 'remove-cycle-in-a-ll', difficulty: 'medium', order: 3, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=-1E8ZMS0gSs', leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Oracle', 'Paytm', 'Google', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 1)', title: 'Detect Cycle in a LL', slug: 'detect-cycle-in-a-ll', difficulty: 'easy', order: 4, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=-1E8ZMS0gSs', leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Meta', 'Cisco', 'Wipro', 'Samsung', 'Goldman Sachs', 'Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 1)', title: 'Merge 2 Sorted LL', slug: 'merge-2-sorted-ll', difficulty: 'easy', order: 5, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=f8RPIb-0DDE', leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/description/', articleUrl: 'https://dsa.apnacollege.in/merge-2-sorted-ll', codeforcesUrl: '' }, tags: [], companyTags: ['Synopsys', 'FactSet', 'Brocade', 'Amazon', 'Flipkart', 'MakeMyTrip', 'Microsoft', 'OATS', 'Oracle', 'Samsung', 'Zoho', 'Accolite'], avgTime: '10-20 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 1)', title: 'Flatten a Linked List', slug: 'flatten-a-linked-list', difficulty: 'medium', order: 6, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=I8b0rff5F9M', leetcodeUrl: 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Apple', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 2)', title: 'Is LL a Palindrome or Not', slug: 'is-ll-a-palindrome-or-not', difficulty: 'easy', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/palindrome-linked-list/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Qualcomm', 'Oracle', 'Adobe', 'Google', 'Uber', 'Amazon', 'Microsoft'], avgTime: '10-20 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 2)', title: 'Clone List with Random Pointers', slug: 'clone-list-with-random-pointers', difficulty: 'medium', order: 8, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=8ze7Zopdsaw', leetcodeUrl: 'https://leetcode.com/problems/copy-list-with-random-pointer/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Nvidia', 'Intel', 'Oracle', 'Amazon', 'Microsoft', 'Google', 'Flipkart', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 2)', title: 'Reverse Linked List II', slug: 'reverse-linked-list-ii', difficulty: 'medium', order: 9, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Adobe', 'Microsoft', 'Amazon', 'Meta', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 2)', title: 'Add 2 Numbers', slug: 'add-2-numbers', difficulty: 'medium', order: 10, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/add-two-numbers/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Amazon', 'Oracle', 'Google', 'Tejas network', 'Josh technology', 'TCS', 'Accenture'], avgTime: '20-30 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 2)', title: 'Reverse Nodes in K Groups', slug: 'reverse-nodes-in-k-groups', difficulty: 'hard', order: 11, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=-swgIiMIlJo', leetcodeUrl: 'https://leetcode.com/problems/reverse-nodes-in-k-group/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Salesforce', 'Apple', 'Infosys', 'Microsoft', 'Google', 'Amazon'], avgTime: '40-60 min' },
  { topicSlug: 'linked-list', subtopic: 'Linked List (Part 2)', title: 'Rotate a Linked List', slug: 'rotate-a-linked-list', difficulty: 'medium', order: 12, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/rotate-list/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Infosys', 'Nvidia', 'Meta', 'Morgan Stanley', 'Siemens', 'Adobe', 'Oracle', 'Amazon', 'Microsoft', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 1)', title: 'Implement Stack using Queue', slug: 'implement-stack-using-queue', difficulty: 'easy', order: 1, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=sFvP5Ois0CE', leetcodeUrl: 'https://leetcode.com/problems/implement-stack-using-queues/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Oracle', 'Adobe', 'Microsoft', 'Amazon', 'Meta', 'Optum'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 1)', title: 'Next Greater Element I', slug: 'next-greater-element', difficulty: 'easy', order: 2, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=NKbExYwvjb0', leetcodeUrl: 'https://leetcode.com/problems/next-greater-element-i/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Microsoft', 'Meta', 'Swiggy', 'Amazon', 'Google', 'Morgan Stanley', 'Oracle'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 1)', title: 'Implement Queue using Stack', slug: 'implement-queue-using-stack', difficulty: 'easy', order: 3, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=sFvP5Ois0CE', leetcodeUrl: 'https://leetcode.com/problems/implement-queue-using-stacks/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Amazon', 'Google', 'Microsoft', 'Oracle', 'Uber'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 1)', title: 'Valid Parenthesis', slug: 'valid-parenthesis', difficulty: 'easy', order: 4, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=NlHupEeDXzY', leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'TCS', 'JP morgan', 'Meta', 'Linkedin', 'Intuit', 'Google', 'Visa', 'IBM'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 1)', title: '1st Non Repeating in Stream', slug: '1st-non-repeating-in-stream', difficulty: 'easy', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/first-unique-character-in-a-string/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'TCS', 'Meta', 'Amazon', 'Goldman Sachs', 'Microsoft', 'Adobe'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 1)', title: 'Reverse 1st K Elements of Queue', slug: 'reverse-1st-k-elements-of-queue-2', difficulty: 'easy', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Amdocs', 'Microsoft'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 2)', title: 'Time needed to Buy Tickets', slug: 'time-needed-to-buy-tickets', difficulty: 'easy', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/time-needed-to-buy-tickets/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Meta', 'Microsoft', 'Amazon', 'Google'], avgTime: '10-20 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 2)', title: 'LRU Cache', slug: 'lru-cache', difficulty: 'medium', order: 8, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=GsY6y0iPaHw', leetcodeUrl: 'https://leetcode.com/problems/lru-cache/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Miro', 'Ebay', 'Microsoft', 'Uber', 'Visa', 'Oracle', 'Intuit', 'Samsung', 'PayPal'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 2)', title: 'Get Min Element from Stack', slug: 'get-min-element-from-stack', difficulty: 'medium', order: 9, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=wHDm-N2m2XY', leetcodeUrl: 'https://leetcode.com/problems/min-stack/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Meta', 'Nike', 'Google', 'Intuit', 'PayPal', 'Adobe', 'Salesforce'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 2)', title: 'Next Smaller Element', slug: 'next-smaller-element', difficulty: 'medium', order: 10, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/immediate-smaller-element1142/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 2)', title: 'Celebrity Problem', slug: 'celebrity-problem', difficulty: 'medium', order: 11, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=OZPmEA_8FM8', leetcodeUrl: 'https://leetcode.com/problems/find-the-celebrity/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Linkedin', 'Uber', 'Salesforce', 'Microsoft', 'Amazon', 'Phone Pe'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 3)', title: 'Rotten Oranges', slug: 'rotten-oranges', difficulty: 'medium', order: 12, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Flipkart', 'Intuit', 'Samsung', 'Oracle', 'Meta', 'Phone Pe', 'Microsoft', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 3)', title: 'Sort a Stack', slug: 'sort-a-stack', difficulty: 'medium', order: 13, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/sort-a-stack/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Goldman Sachs', 'IBM', 'Intuit', 'Microsoft', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 3)', title: 'Stock Span', slug: 'stock-span', difficulty: 'medium', order: 14, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/online-stock-span/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Google', 'Amazon', 'Apple', 'Adobe', 'Meta'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 3)', title: 'Circular Tour / Gas Station', slug: 'circular-tour-gas-station', difficulty: 'medium', order: 15, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=SmTow5Ht4iU', leetcodeUrl: 'https://leetcode.com/problems/gas-station/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Salesforce', 'Adobe', 'Oracle', 'Google', 'Microsoft', 'Amazon', 'Meta', 'Cisco', 'Infosys', 'Bank of Newyork'], avgTime: '20-30 min' },
  { topicSlug: 'stacks-queues', subtopic: 'Stacks & Queues (Part 3)', title: 'Max Area in Histogram', slug: 'max-area-in-histogram', difficulty: 'hard', order: 16, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=ysy1o-QEj3k&t=4s', leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['TCS', 'Uber', 'Meta', 'Google', 'Amazon', 'Microsoft', 'Adobe', 'DE Shaw'], avgTime: '40-60 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 1)', title: 'Preorder Traversal', slug: 'preorder-traversal', difficulty: 'easy', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-preorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Salesforce', 'Amazon', 'Microsoft', 'Google', 'Adobe', 'Meta'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 1)', title: 'Level Order Traversal', slug: 'level-order-traversal', difficulty: 'medium', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Google', 'Oracle', 'Apple', 'Meta', 'Uber', 'Intuit', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 1)', title: 'Inorder Traversal', slug: 'inorder-traversal', difficulty: 'easy', order: 3, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-inorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Uber', 'Meta', 'Google', 'Amazon', 'Microsoft'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 1)', title: 'Minimum Distance between Nodes', slug: 'minimum-distance-between-nodes', difficulty: 'easy', order: 4, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=WZmjRXF_Zi4', leetcodeUrl: 'https://leetcode.com/problems/minimum-distance-between-bst-nodes/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Google'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 1)', title: 'Symmetric Tree', slug: 'symmetric-tree', difficulty: 'easy', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/symmetric-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Amazon', 'Google', 'Linkedin', 'Microsoft'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 1)', title: 'Postorder Traversal', slug: 'postorder-traversal-2', difficulty: 'easy', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-postorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Adobe', 'Google', 'Amazon', 'Meta'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 2)', title: 'Morris Inorder Traversal', slug: 'morris-inorder-traversal', difficulty: 'easy', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-inorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Google', 'Apple', 'Adobe', 'Microsoft', 'Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 2)', title: 'Diameter of a Tree', slug: 'diameter-of-a-tree', difficulty: 'easy', order: 8, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=aPyDPImR5UM', leetcodeUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Oracle', 'Visa', 'Google', 'Amazon', 'Meta', 'TCS'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 2)', title: 'Are 2 Trees Identical or Not', slug: 'are-2-trees-identical-or-not', difficulty: 'easy', order: 9, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/same-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Meta', 'Apple', 'TCS', 'Amazon', 'Google', 'Flipkart', 'Uber', 'Linkedin'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 2)', title: 'Check if BT Mirror of itself or not', slug: 'check-if-bt-mirror-of-itself-or-not', difficulty: 'easy', order: 10, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/symmetric-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Google', 'Linkedin', 'Adobe', 'Microsoft', 'Meta', 'Apple'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 2)', title: 'Subtree of Another Tree', slug: 'subtree-of-another-tree', difficulty: 'easy', order: 11, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=tumW7jsjv68', leetcodeUrl: 'https://leetcode.com/problems/subtree-of-another-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Morgan Stanley', 'Uber', 'Ebay', 'Google', 'Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 2)', title: 'Is Tree Height Balanced', slug: 'is-tree-height-balanced', difficulty: 'easy', order: 12, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=7tzHzN_Ehus', leetcodeUrl: 'https://leetcode.com/problems/balanced-binary-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Adobe', 'Uber', 'Google', 'Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 3)', title: 'Bottom View of a Tree', slug: 'bottom-view-of-a-tree', difficulty: 'medium', order: 13, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Google', 'Adobe', 'Josh technology'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 3)', title: 'Top View of a Tree', slug: 'top-view-of-a-tree', difficulty: 'medium', order: 14, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=FGr-syrhvOA', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Accolite', 'Flipkart', 'Oracle', 'Uber', 'JP morgan', 'Google', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 3)', title: 'Lowest Common Ancestor (LCA)', slug: 'lowest-common-ancestor-lca', difficulty: 'medium', order: 15, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=oX5D0uKOMck', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Morgan Stanley', 'Salesforce', 'Flipkart', 'Adobe', 'Oracle', 'Linkedin', 'Intuit', 'Google', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 3)', title: 'Kth Level of Tree', slug: 'kth-level-of-tree', difficulty: 'medium', order: 16, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=ze4JO_ODl3w', leetcodeUrl: 'https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Microsoft', 'Google', 'Amazon', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 3)', title: 'Construct BT from Inorder & Preorder', slug: 'construct-bt-from-inorder-preorder', difficulty: 'medium', order: 17, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=33b1M980cCA', leetcodeUrl: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Microsoft', 'Amazon', 'VMWare', 'Uber', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 3)', title: 'Transform to Sum Tree', slug: 'transform-to-sum-tree', difficulty: 'medium', order: 18, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=TY6kEejJEM0', leetcodeUrl: 'https://leetcode.com/problems/binary-search-tree-to-greater-sum-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Microsoft', 'Ebay', 'SAP Labs'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 4)', title: 'Flatten BT to LL', slug: 'flatten-bt-to-ll', difficulty: 'medium', order: 19, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=dU2Z5HWSGM0', leetcodeUrl: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Apple', 'Google', 'Amazon', 'Oracle', 'Adobe', 'Myntra'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 4)', title: 'Max Path Sum', slug: 'max-path-sum', difficulty: 'hard', order: 20, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Goldman Sachs', 'Salesforce', 'Oracle', 'Amazon', 'Google', 'Uber', 'Flipkart'], avgTime: '40-60 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 4)', title: 'Max Width of BT', slug: 'max-width-of-bt', difficulty: 'medium', order: 21, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=rhz-csskg_A', leetcodeUrl: 'https://leetcode.com/problems/maximum-width-of-binary-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Google', 'Adobe', 'Microsoft', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 4)', title: 'Construct BT from Inorder & Postorder', slug: 'construct-bt-from-inorder-postorder', difficulty: 'medium', order: 22, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Bloomberg', 'Google', 'Adobe', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 4)', title: 'Zig Zag Traversal of BT', slug: 'zig-zag-traversal-of-bt', difficulty: 'medium', order: 23, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Adobe', 'Ebay', 'Flipkart', 'Microsoft', 'Amazon', 'Meta', 'Oracle'], avgTime: '20-30 min' },
  { topicSlug: 'binary-trees', subtopic: 'Binary Trees (Part 4)', title: 'Kth Ancestor', slug: 'kth-ancestor', difficulty: 'hard', order: 24, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/kth-ancestor-of-a-tree-node/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Amazon', 'Google'], avgTime: '40-60 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 1)', title: 'Kth largest in BST', slug: 'kth-largest-in-bst', difficulty: 'easy', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Adobe', 'Salesforce', 'Google', 'Atlassian', 'Meta'], avgTime: '10-20 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 1)', title: 'Sorted Array to Balanced BST', slug: 'sorted-array-to-balanced-bst', difficulty: 'easy', order: 2, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=0s6sCjs_4g0', leetcodeUrl: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Airbnb', 'Google', 'Amazon', 'Samsung'], avgTime: '10-20 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 1)', title: 'Kth Smallest in BST', slug: 'kth-smallest-in-bst', difficulty: 'medium', order: 3, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=Kq4BbvIhj44', leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Google', 'Accolite', 'Amazon', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 1)', title: 'LCA in BST', slug: 'lca-in-bst', difficulty: 'medium', order: 4, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=ORxkZ12FrU4', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Apple', 'Bloomberg', 'Amazon', 'Linkedin', 'Oracle', 'Samsung'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 1)', title: 'Validate BST', slug: 'validate-bst', difficulty: 'medium', order: 5, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=dSBcCynP1nA&t=21s', leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Citadel', 'Uber', 'Salesforce', 'Google', 'IBM', 'Adobe', 'Oracle', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 2)', title: 'Recover BST', slug: 'recover-bst', difficulty: 'medium', order: 6, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=0KGzfij_SCk', leetcodeUrl: 'https://leetcode.com/problems/recover-binary-search-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Oracle', 'Google', 'Amazon', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 2)', title: 'Populate Next Right Pointers', slug: 'populate-next-right-pointers', difficulty: 'medium', order: 7, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=a8VKpW1DsD8', leetcodeUrl: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Adobe', 'Flipkart', 'Salesforce', 'Oracle'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 2)', title: 'Construct from Preorder', slug: 'construct-from-preorder', difficulty: 'medium', order: 8, resources: { youtubeUrl: 'https://youtu.be/-n5Ur1wE5Jc?si=Bh0ukUvFtj3p1Ku8', leetcodeUrl: 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Google', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 2)', title: 'BST Iterator', slug: 'bst-iterator', difficulty: 'medium', order: 9, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=dS1bKglre3A', leetcodeUrl: 'https://leetcode.com/problems/binary-search-tree-iterator/description/', articleUrl: 'https://dsa.apnacollege.in/bst-iterator', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Linkedin', 'Microsoft', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 2)', title: 'Flatten BST to Sorted list', slug: 'flatten-bst-to-sorted-list', difficulty: 'medium', order: 10, resources: { youtubeUrl: 'https://youtu.be/dU2Z5HWSGM0?si=wyQANxRxIlsJsDoC', leetcodeUrl: 'https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Nvidia', 'Microsoft', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 3)', title: 'Merge 2 BSTs', slug: 'merge-2-bsts', difficulty: 'hard', order: 11, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=AiKZjCuy2k4', leetcodeUrl: 'https://leetcode.com/problems/merge-bsts-to-create-single-bst/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Bloomberg', 'Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 3)', title: 'Serialize & Deserialize BST', slug: 'serialize-deserialize-bst', difficulty: 'hard', order: 12, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Amazon', 'Google', 'Linkedin', 'Uber', 'Intuit', 'Qualcomm', 'Citadel', 'Nvidia'], avgTime: '40-60 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 3)', title: 'Inorder Predecessor', slug: 'inorder-predecessor', difficulty: 'medium', order: 13, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=IHNkql1tAnk', leetcodeUrl: 'https://leetcode.com/problems/delete-node-in-a-bst/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Flipkart', 'Oracle', 'Google', 'Amazon', 'Adobe', 'Meta', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 3)', title: 'Largest BST in BT', slug: 'largest-bst-in-bt', difficulty: 'medium', order: 14, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=Pr-HFxp7npk', leetcodeUrl: 'https://leetcode.com/problems/largest-bst-subtree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Meta'], avgTime: '40-60 min' },
  { topicSlug: 'bst', subtopic: 'BST (Part 3)', title: 'Inorder Successor', slug: 'inorder-successor', difficulty: 'medium', order: 15, resources: { youtubeUrl: 'https://www.youtube.com/watch?v=IHNkql1tAnk', leetcodeUrl: 'https://leetcode.com/problems/inorder-successor-in-bst/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Meta'], avgTime: '20-30 min' },
  { topicSlug: 'heaps', subtopic: 'Heaps', title: 'Merge K Sorted Arrays', slug: 'merge-k-sorted-arrays', difficulty: 'easy', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/merge-sorted-array/description/?envType=problem-list-v2&envId=sorting', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Cisco', 'Amazon', 'IBM', 'Oracle', 'Adobe', 'Google', 'HCL', 'Microsoft'], avgTime: '10-20 min' },
  { topicSlug: 'heaps', subtopic: 'Heaps', title: 'K most Frequent Elements', slug: 'k-most-frequent-elements', difficulty: 'medium', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Salesforce', 'Microsoft', 'Amazon', 'Google', 'Oracle', 'Goldman Sachs', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'heaps', subtopic: 'Heaps', title: 'Median from Stream', slug: 'median-from-stream', difficulty: 'hard', order: 3, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Pinterest', 'Google', 'Apple', 'Amazon', 'Goldman Sachs', 'Microsoft', 'PayPal', 'Oracle', 'Meta'], avgTime: '40-60 min' },
  { topicSlug: 'heaps', subtopic: 'Heaps', title: 'Smallest Range in K Sorted List', slug: 'smallest-range-in-k-sorted-list', difficulty: 'hard', order: 4, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Phone Pe', 'Flipkart', 'DE Shaw', 'Amazon', 'Meta', 'Adobe', 'Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'heaps', subtopic: 'Heaps', title: 'Kth Smallest Element', slug: 'kth-smallest-element', difficulty: 'medium', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/description/?envType=problem-list-v2&envId=sorting', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Phone Pe', 'Salesforce', 'Apple', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'heaps', subtopic: 'Heaps', title: 'Heap Sort', slug: 'heap-sort', difficulty: 'medium', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/sort-an-array/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Oracle', 'Google', 'Amazon', 'Adobe', 'TCS', 'Infosys', 'Meta', 'Apple'], avgTime: '20-30 min' },
  { topicSlug: 'tries', subtopic: 'Tries', title: 'Word Break Problem', slug: 'word-break-problem', difficulty: 'medium', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/word-break/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Flipkart', 'Amazon', 'Google', 'Netflix', 'Intuit', 'Uber', 'Walmart', 'Salesforce', 'Oracle'], avgTime: '20-30 min' },
  { topicSlug: 'tries', subtopic: 'Tries', title: 'Implement a Trie', slug: 'implement-a-trie', difficulty: 'medium', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Nvidia', 'Google', 'Uber', 'Samsung', 'Amazon', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'tries', subtopic: 'Tries', title: 'Longest String with All Prefix', slug: 'longest-string-with-all-prefix', difficulty: 'medium', order: 3, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-word-with-all-prefixes/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google'], avgTime: '20-30 min' },
  { topicSlug: 'tries', subtopic: 'Tries', title: 'Implement a Phone Directory', slug: 'implement-a-phone-directory', difficulty: 'medium', order: 4, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/design-phone-directory/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google'], avgTime: '20-30 min' },
  { topicSlug: 'tries', subtopic: 'Tries', title: 'Longest Common Prefix', slug: 'longest-common-prefix-2', difficulty: 'easy', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Visa', 'Oracle', 'Amazon', 'TCS', 'Accenture', 'Infosys', 'Deloitte', 'Google'], avgTime: '10-20 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 1)', title: 'DFS : Depth First Search', slug: 'dfs-depth-first-search', difficulty: 'medium', order: 1, resources: { youtubeUrl: 'https://youtu.be/3czYbhac160?si=x2Z0M_2JhXz2J8zr', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Samsung', 'Intuit', 'Amazon', 'Accolite'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 1)', title: 'BFS : Breadth First Search', slug: 'bfs-breadth-first-search', difficulty: 'medium', order: 2, resources: { youtubeUrl: 'https://youtu.be/scQITTLgFJo?si=wWP38t1K-etIUYRr', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Samsung', 'Adobe', 'Amazon', 'Flipkart', 'Ola', 'SAP Labs'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 1)', title: 'Detect Cycle in Undirected using BFS', slug: 'detect-cycle-in-undirected-using-bfs', difficulty: 'medium', order: 3, resources: { youtubeUrl: 'https://youtu.be/MIjOkApZ39g?si=2JoLLAipBhDTi_N5', leetcodeUrl: 'https://leetcode.com/problems/course-schedule/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Visa', 'Flipkart', 'Amazon', 'Google', 'Adobe', 'Microsoft', 'Oracle'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 1)', title: 'Detect Cycle in Undirected using DFS', slug: 'detect-cycle-in-undirected-using-dfs', difficulty: 'medium', order: 4, resources: { youtubeUrl: 'https://youtu.be/OZClCpPQDR4?si=LHmPSDxyURUIDxsD', leetcodeUrl: 'https://leetcode.com/problems/course-schedule/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Visa', 'Oracle', 'Microsoft', 'Adobe', 'Flipkart', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 1)', title: 'Detect Cycle in Directed using DFS', slug: 'detect-cycle-in-directed-using-dfs', difficulty: 'medium', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/redundant-connection/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Google', 'Amazon', 'InMobi'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 1)', title: 'Detect Cycle in Directed using BFS', slug: 'detect-cycle-in-directed-using-bfs', difficulty: 'medium', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/redundant-connection/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon', 'InMobi', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 2)', title: 'Topological Sorting (DFS)', slug: 'topological-sorting-dfs', difficulty: 'medium', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/topological-sort/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Visa', 'Moonfrog Labs', 'Morgan Stanley', 'DE Shaw', 'Flipkart', 'Samsung', 'OYO', 'Microsoft', 'Accolite', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 2)', title: 'Flood Fill Algorithm', slug: 'flood-fill-algorithm', difficulty: 'easy', order: 8, resources: { youtubeUrl: 'https://youtu.be/JI_e2RzARbM?si=WGTSPN-KWL0C4a9q', leetcodeUrl: 'https://leetcode.com/problems/flood-fill/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Uber', 'Amazon', 'Yahoo', 'Adobe', 'Apple', 'Google', 'Microsoft'], avgTime: '10-20 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 2)', title: 'Topological Sorting (BFS)', slug: 'topological-sorting-bfs', difficulty: 'medium', order: 9, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/topological-sort/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Moonfrog Labs', 'Visa', 'Samsung', 'OYO', 'DE Shaw', 'Flipkart', 'Morgan Stanley', 'Accolite', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 2)', title: 'Course Schedule II', slug: 'course-schedule-ii', difficulty: 'medium', order: 10, resources: { youtubeUrl: 'https://youtu.be/rZsgWxodGmM?si=OgsOy5YcwN41QYwm', leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Nvidia', 'Meta', 'Microsoft', 'Intuit', 'Linkedin', 'Salesforce', 'Google', 'Amazon', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 2)', title: 'Cheapest Flights within K Stops', slug: 'cheapest-flights-within-k-stops', difficulty: 'medium', order: 11, resources: { youtubeUrl: 'https://youtu.be/CLmykzpeCCs?si=VSbiBnnh-v9PNl6v', leetcodeUrl: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Stripe', 'Amazon', 'Airbnb', 'Oracle', 'DE Shaw'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 2)', title: 'Dijkstra\'s Algorithm', slug: 'dijkstras-algorithm-2', difficulty: 'hard', order: 12, resources: { youtubeUrl: 'https://youtu.be/8gYBHjtjWBI?si=nymThY9oC_NcAMPE', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Flipkart', 'Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: 'Kruskal\'s Algorithm (MST)', slug: 'kruskals-algorithm-mst', difficulty: 'hard', order: 13, resources: { youtubeUrl: 'https://youtu.be/inoM6jwj1CA?si=oI5j5RHPlq_syIOT', leetcodeUrl: 'https://leetcode.com/problems/min-cost-to-connect-all-points/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['DE Shaw', 'Uber', 'Directi', 'Amazon', 'Adobe', 'Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: 'Prim\'s Algorithm (MST)', slug: 'prims-algorithm-mst', difficulty: 'hard', order: 14, resources: { youtubeUrl: 'https://youtu.be/Sflh1z6cIMk?si=a-giZuHw0ZKhq7pm', leetcodeUrl: 'https://leetcode.com/problems/min-cost-to-connect-all-points/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Directi', 'Uber', 'Adobe', 'Amazon', 'DE Shaw'], avgTime: '40-60 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: 'Rotting Oranges', slug: 'rotting-oranges', difficulty: 'medium', order: 15, resources: { youtubeUrl: 'https://youtu.be/RmXo5SWkhCs?si=PekrhTqJxNbimhVp', leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Facebook', 'Phone Pe', 'Oracle', 'Citadel', 'Meta', 'Amazon', 'Zoho', 'Salesforce', 'Flipkart', 'Google', 'Intuit', 'Samsung'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: 'Clone a Graph', slug: 'clone-a-graph', difficulty: 'medium', order: 16, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/clone-graph/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon', 'Meta', 'Uber', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: 'Floyd Warshall Algorithm', slug: 'floyd-warshall-algorithm', difficulty: 'hard', order: 17, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Amazon', 'Microsoft', 'Google', 'Uber'], avgTime: '40-60 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: 'Bellman Ford Algorithm', slug: 'bellman-ford-algorithm', difficulty: 'hard', order: 18, resources: { youtubeUrl: 'https://youtu.be/3rFHlbJ7qKc?si=nSmurlJ6tWbk0ymU', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/0', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Directi', 'Sharechat', 'Microsoft', 'Amazon'], avgTime: '40-60 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 3)', title: '01 Matrix', slug: '01-matrix', difficulty: 'medium', order: 19, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/01-matrix/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Linkedin', 'Doordash', 'Google', 'Amazon', 'Flipkart', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'medium', order: 20, resources: { youtubeUrl: 'https://youtu.be/AME6baBpswY?si=0zFCNvVP0GX8e7U7', leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Linkedin', 'Amazon', 'Meta', 'Nvidia', 'Apple', 'Adobe', 'Goldman Sachs', 'Microsoft', 'Oracle', 'PayPal', 'Salesforce'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Is Graph Bipartite?', slug: 'is-graph-bipartite', difficulty: 'medium', order: 21, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/is-graph-bipartite/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Samsung', 'Meta', 'Pinterest', 'Microsoft', 'Flipkart', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Strongly Connected Components (Kosaraju\'s)', slug: 'strongly-connected-components-kosarajus', difficulty: 'hard', order: 22, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Paytm'], avgTime: '40-60 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Most Stones Removed', slug: 'most-stones-removed', difficulty: 'medium', order: 23, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Amazon', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Number of Ways to Arrive at Destination', slug: 'number-of-ways-to-arrive-at-destination', difficulty: 'medium', order: 24, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Number of Provinces', slug: 'number-of-provinces', difficulty: 'medium', order: 25, resources: { youtubeUrl: 'https://youtu.be/J1yCPIP-K8s?si=I86S3sfHWkRMrNxb', leetcodeUrl: 'https://leetcode.com/problems/number-of-provinces/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Meta', 'Sprinklr', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'graphs', subtopic: 'Graphs (Part 4)', title: 'Alien Dictionary', slug: 'alien-dictionary', difficulty: 'hard', order: 26, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/alien-dictionary/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Citadel', 'Google', 'Airbnb', 'Uber'], avgTime: '40-60 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 1)', title: '0-1 Knapsack', slug: '0-1-knapsack', difficulty: 'medium', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1', articleUrl: 'https://dsa.apnacollege.in/0-1-knapsack', codeforcesUrl: '' }, tags: [], companyTags: ['Directi', 'Morgan Stanley', 'Oracle', 'Snapdeal', 'Amazon', 'Visa', 'Mobicip', 'Microsoft', 'GreyOrange', 'Flipkart', 'Payu'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 1)', title: 'Buy & Sell Stocks I', slug: 'buy-sell-stocks-i', difficulty: 'easy', order: 2, resources: { youtubeUrl: 'https://youtu.be/WBzZCm46mFo?si=0HH8sY1_cmD_h2rz', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Directi', 'Goldman Sachs', 'Microsoft', 'Google', 'Media.Net', 'MakeMyTrip', 'Intuit', 'Flipkart', 'DE Shaw', 'Quikr', 'Walmart', 'Swiggy', 'Salesforce', 'Paytm', 'Pubmatic', 'Oracle', 'Ola'], avgTime: '10-20 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 1)', title: 'Target Sum Subset', slug: 'target-sum-subset', difficulty: 'medium', order: 3, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/target-sum/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Myntra', 'Meta', 'Amazon', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 1)', title: 'Coin Change', slug: 'coin-change', difficulty: 'medium', order: 4, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/coin-change/description/', articleUrl: 'https://dsa.apnacollege.in/coin-change', codeforcesUrl: '' }, tags: [], companyTags: ['Salesforce', 'Microsoft', 'Intuit', 'Google', 'Amazon', 'Adobe', 'Accenture', 'Infosys'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 1)', title: 'Unbounded Knapsack', slug: 'unbounded-knapsack', difficulty: 'medium', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 2)', title: 'Longest Common Substring', slug: 'longest-common-substring', difficulty: 'medium', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/longest-common-substring1452/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Microsoft', 'Morgan Stanley'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 2)', title: 'Longest Common Subsequence', slug: 'longest-common-subsequence', difficulty: 'medium', order: 7, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-common-subsequence/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Oracle', 'Amazon', 'Google', 'TCS', 'Microsoft', 'Meta'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 2)', title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'medium', order: 8, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Salesforce', 'Google', 'Atlassian', 'PayPal', 'Goldman Sachs', 'Amazon', 'Intuit', 'IBM'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 2)', title: 'Edit Distance', slug: 'edit-distance', difficulty: 'medium', order: 9, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/edit-distance/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Goldman Sachs', 'Google', 'TCS', 'Accenture', 'Rubrik', 'Citrix', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 2)', title: 'Longest Palindromic Subsequence', slug: 'longest-palindromic-subsequence', difficulty: 'medium', order: 10, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-subsequence/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['TCS', 'Linkedin', 'Amazon', 'Google', 'Meta', 'Cisco'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 2)', title: 'Buy & Sell Stocks II', slug: 'buy-sell-stocks-ii', difficulty: 'medium', order: 11, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Adobe', 'TCS', 'Apple', 'Goldman Sachs', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 3)', title: 'Nth Catalan', slug: 'nth-catalan', difficulty: 'medium', order: 12, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/nth-catalan-number0817/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 3)', title: 'Unique BSTs', slug: 'unique-bsts', difficulty: 'medium', order: 13, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/unique-binary-search-trees/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Amazon', 'Oracle', 'Tower Research Capital', 'Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 3)', title: 'Rod Cutting', slug: 'rod-cutting', difficulty: 'hard', order: 14, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Phone Pe', 'Apple', 'Oracle', 'Adobe'], avgTime: '40-60 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 3)', title: 'Palindromic Partitioning', slug: 'palindromic-partitioning', difficulty: 'medium', order: 15, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/palindrome-partitioning/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Infosys', 'Amazon', 'Microsoft', 'Meta', 'Google'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 3)', title: 'MCM', slug: 'mcm', difficulty: 'hard', order: 16, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Walmart', 'Flipkart'], avgTime: '40-60 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 4)', title: 'Minimum Partitioning', slug: 'minimum-partitioning', difficulty: 'hard', order: 17, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Uber', 'Samsung', 'Amazon', 'Meta', 'Arcesium'], avgTime: '40-60 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 4)', title: 'Max Product Subarray', slug: 'max-product-subarray', difficulty: 'medium', order: 18, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Meta', 'Amazon', 'Uber', 'Adobe', 'DE Shaw', 'Linkedin'], avgTime: '20-30 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 4)', title: 'Wildcard Pattern Matching', slug: 'wildcard-pattern-matching', difficulty: 'hard', order: 19, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/wildcard-matching/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Apple', 'Microsoft', 'Amazon', 'Ola', 'Salesforce'], avgTime: '40-60 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 4)', title: 'Longest Bitonic Subsequence', slug: 'longest-bitonic-subsequence', difficulty: 'hard', order: 20, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/minimum-number-of-removals-to-make-mountain-array/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Microsoft', 'Google', 'Meta'], avgTime: '40-60 min' },
  { topicSlug: 'dp', subtopic: 'DP (Part 4)', title: 'Egg Dropping', slug: 'egg-dropping', difficulty: 'hard', order: 21, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/super-egg-drop/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Samsung', 'Philips', 'Myntra', 'Nearbuy', 'Oracle', 'DE Shaw', 'Amazon', 'Hike', 'Google', 'Goldman Sachs', 'MakeMyTrip', 'MAQ Software', 'Unisys', 'VMWare', 'Microsoft'], avgTime: '40-60 min' },
  { topicSlug: 'greedy', subtopic: 'Greedy', title: 'Assign Cookies', slug: 'assign-cookies', difficulty: 'easy', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/assign-cookies/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Google', 'Adobe', 'Uber'], avgTime: '10-20 min' },
  { topicSlug: 'greedy', subtopic: 'Greedy', title: 'Indian Coins', slug: 'indian-coins', difficulty: 'easy', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/-minimum-number-of-coins4426/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Morgan Stanley', 'Visa', 'Snapdeal', 'Accolite', 'Synopsys', 'Google', 'Samsung', 'Oracle', 'Paytm', 'Amazon'], avgTime: '10-20 min' },
  { topicSlug: 'greedy', subtopic: 'Greedy', title: 'Fractional Knapsack', slug: 'fractional-knapsack', difficulty: 'medium', order: 3, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft'], avgTime: '20-30 min' },
  { topicSlug: 'greedy', subtopic: 'Greedy', title: 'Job Scheduling', slug: 'job-scheduling', difficulty: 'medium', order: 4, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/job-sequencing-problem--170647/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Adobe', 'Airbnb', 'Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'greedy', subtopic: 'Greedy', title: 'Activity Selection', slug: 'activity-selection', difficulty: 'medium', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://www.geeksforgeeks.org/problems/activity-selection-1587115620/1', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Microsoft', 'Amazon', 'Google', 'Meta'], avgTime: '20-30 min' },
  { topicSlug: 'greedy', subtopic: 'Greedy', title: 'Max Length of Pair Chain', slug: 'max-length-of-pair-chain', difficulty: 'medium', order: 6, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/maximum-length-of-pair-chain/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon', 'Bloomberg', 'Microsoft', 'Adobe', 'Swiggy'], avgTime: '20-30 min' },
  { topicSlug: 'misc', subtopic: 'Miscellaneous', title: 'Power Set', slug: 'power-set', difficulty: 'medium', order: 1, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/subsets/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google', 'Adobe', 'Atlassian', 'TCS', 'Fiverr', 'Uber'], avgTime: '20-30 min' },
  { topicSlug: 'misc', subtopic: 'Miscellaneous', title: 'Max XOR of Two Numbers', slug: 'max-xor-of-two-nums', difficulty: 'medium', order: 2, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Goldman Sachs', 'Google', 'Amazon', 'Adobe'], avgTime: '20-30 min' },
  { topicSlug: 'misc', subtopic: 'Miscellaneous', title: 'Power of Two', slug: 'power-of-two', difficulty: 'easy', order: 3, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/power-of-two/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Adobe', 'Snapdeal', 'TCS', 'Google', 'Apple'], avgTime: '10-20 min' },
  { topicSlug: 'misc', subtopic: 'Miscellaneous', title: 'XOR Beauty of Array', slug: 'xor-beauty-of-array', difficulty: 'medium', order: 4, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/find-xor-beauty-of-array/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Amazon'], avgTime: '20-30 min' },
  { topicSlug: 'misc', subtopic: 'Miscellaneous', title: 'Watering Plants II', slug: 'watering-plants', difficulty: 'medium', order: 5, resources: { youtubeUrl: '', leetcodeUrl: 'https://leetcode.com/problems/watering-plants-ii/description/', articleUrl: '', codeforcesUrl: '' }, tags: [], companyTags: ['Google'], avgTime: '20-30 min' },
];

async function seed(): Promise<void> {
  console.log('🌱 Connecting to database...');
  await mongoose.connect(env.MONGODB_URI);

  console.log('🗑️  Clearing existing data...');
  await Promise.all([Topic.deleteMany({}), Problem.deleteMany({})]);

  console.log('📚 Inserting topics...');
  const topics = await Topic.insertMany(TOPICS);
  const topicMap = new Map(topics.map((t) => [t.slug, t._id]));

  console.log('📝 Inserting problems...');
  const problems = PROBLEMS.map((p) => ({
    ...p,
    topicId: topicMap.get(p.topicSlug),
  }));
  await Problem.insertMany(problems);

  console.log('📊 Updating problem counts...');
  for (const topic of topics) {
    const count = await Problem.countDocuments({ topicId: topic._id });
    await Topic.findByIdAndUpdate(topic._id, { problemCount: count });
  }

  console.log('👤 Creating seed users...');
  const demoHash = await bcrypt.hash('Demo@1234', 12);
  const adminHash = await bcrypt.hash('Admin@1234', 12);

  await User.findOneAndUpdate(
    { email: 'demo@codepath.com' },
    { name: 'Demo User', email: 'demo@codepath.com', passwordHash: demoHash, role: 'student' },
    { upsert: true }
  );

  await User.findOneAndUpdate(
    { email: 'admin@codepath.com' },
    { name: 'Admin User', email: 'admin@codepath.com', passwordHash: adminHash, role: 'admin' },
    { upsert: true }
  );

  console.log(`✅ Seed complete! ${topics.length} topics, ${problems.length} problems.`);
  console.log('   Demo  → demo@codepath.com / Demo@1234');
  console.log('   Admin → admin@codepath.com / Admin@1234');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
